name: 'Release'

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  build-release-and-publish:
    name: 'Build and Publish Assets built for Releases'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          path: 'frappe'

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Set up bench and build assets
        run: |
          npm install -g yarn
          pip3 install -U frappe-bench
          bench -v init frappe-bench --no-procfile --no-backups --skip-assets --skip-redis-config-generation --python $(which python) --frappe-path $GITHUB_WORKSPACE/frappe
          cd frappe-bench && bench build

      - name: Package assets
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          tar -cvpzf $GITHUB_WORKSPACE/build/assets.tar.gz ./frappe-bench/sites/assets/frappe/dist

      - name: Upload built Assets to Release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: >-
          gh release upload "$RELEASE_TAG" "$GITHUB_WORKSPACE/build/assets.tar.gz"
          --clobber --repo "$GITHUB_REPOSITORY"
